service: todotada-application-backend

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs12.x


functions:
  todotada:
    handler: handler.app
    environment:
      DB_HOST: ${opt:DB_HOST}
      DB_USER: ${opt:DB_USER}
      DB_PASSWORD: ${opt:DB_PASSWORD}
    events:
      - http:
         method: get
         path: todotada
         cors: true
      - http:
          method: put
          path: todotada/{id}
          cors: true
      - http:
          method: delete
          path: todotada/{id}
          cors: true
      - http:
          method: post
          path: todotada
          cors: true

